/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2015-01-11 05:52:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/chat/header.jsp", Long.valueOf(1420955346000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Written by Sukhwinder Singh (ssruprai@hotmail.com -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String nickname = (String)session.getAttribute("nickname");
	if (nickname != null)
	{
		response.sendRedirect("listrooms.jsp");
	}

      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("  <HEAD>\r\n");
      out.write("    <TITLE>\r\n");
      out.write("      S2R Chat - Login\r\n");
      out.write("    </TITLE>\r\n");
      out.write("\t <META http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t <meta name=\"Author\" content=\"Sukhwinder Singh (ssruprai@hotmail.com\">\t\r\n");
      out.write("\t <script language=\"JavaScript\">\r\n");
      out.write("\t <!--\r\n");
      out.write("\t if(window.top != window.self)\r\n");
      out.write("\t {\r\n");
      out.write("\t\t window.top.location = window.location;\r\n");
      out.write("\t }\r\n");
      out.write("\t //-->\r\n");
      out.write("\t </script>\r\n");
      out.write("\t <LINK rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/chat.css\">\r\n");
      out.write("\t <META name=\"author\" content=\"Sukhwinder Singh (ssruprai@hotmail.com)\">\r\n");
      out.write("\t</HEAD>\r\n");
      out.write("\t<BODY bgcolor=\"#FFFFFF\" onLoad=\"document.login.nickname.focus();\">\r\n");
      out.write("\t");
      out.write("<div align=\"center\">\r\n");
      out.write("<center>\r\n");
      out.write("<table width=\"100%\" border=\"0\">\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"100%\" class=\"title\">S2R Chat</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("<br>");
      out.write("\r\n");
      out.write("    <TABLE width=\"40%\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\" align=\"center\">\r\n");
      out.write("      ");

      String d=request.getParameter("d");
      String n=request.getParameter("n");
      String ic = request.getParameter("ic");
		
          if (d!=null && d.equals("t"))
          {
      
      out.write("\r\n");
      out.write("      <TR>\r\n");
      out.write("        <TD>\r\n");
      out.write("          <TABLE width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\" align=\"center\">\r\n");
      out.write("            <TR>\r\n");
      out.write("              <TD colspan=\"2\" align=\"center\">\r\n");
      out.write("                <SPAN class=\"error\">Nickname exists</SPAN><BR>\r\n");
      out.write("              </TD>\r\n");
      out.write("            </TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("              <TD colspan=\"2\">\r\n");
      out.write("                Nickname <B>");
      out.print(n);
      out.write("</B> has already been taken please select some other nick.\r\n");
      out.write("              </TD>\r\n");
      out.write("            </TR>\r\n");
      out.write("          </TABLE>\r\n");
      out.write("        </TD>\r\n");
      out.write("      </TR>\r\n");
      out.write("      ");

        }
        else if (ic!=null && ic.equals("t"))
        {
      
      out.write("\r\n");
      out.write("      <TR>\r\n");
      out.write("        <TD colspan=\"2\">\r\n");
      out.write("          <TABLE width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"1\" align=\"center\">\r\n");
      out.write("            <TR>\r\n");
      out.write("              <TD colspan=\"2\" align=\"center\">\r\n");
      out.write("                <SPAN class=\"error\">Incomplete information</SPAN>\r\n");
      out.write("              </TD>\r\n");
      out.write("            </TR>\r\n");
      out.write("\t\t\t\t<TR>\r\n");
      out.write("              <TD colspan=\"2\">\r\n");
      out.write("                <b>Sex</b> and <b>Nickname</b> must be entered and nickname must be atleast <b>4</b> characters long and must not contain any <b>space</b>.\r\n");
      out.write("              </TD>\r\n");
      out.write("            </TR>\r\n");
      out.write("          </TABLE>\r\n");
      out.write("        </TD>\r\n");
      out.write("      </TR>\r\n");
      out.write("      ");

        }
      
      out.write("\r\n");
      out.write("      <TR>\r\n");
      out.write("        <TD colspan=\"2\" class=\"panel\">\r\n");
      out.write("          <FORM name=\"login\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/chat/servlet/login\">\r\n");
      out.write("            <TABLE width=\"100%\" border=\"0\">\r\n");
      out.write("              <TR>\r\n");
      out.write("                <TD width=\"30%\" class=\"white\">\r\n");
      out.write("                  Nickname\r\n");
      out.write("                </TD>\r\n");
      out.write("                <TD width=\"70%\">\r\n");
      out.write("                  <INPUT type=\"text\" name=\"nickname\" size=\"15\">\r\n");
      out.write("                </TD>\r\n");
      out.write("              </TR>\r\n");
      out.write("              <TR>\r\n");
      out.write("                <TD width=\"30%\" class=\"white\">\r\n");
      out.write("                  Sex\r\n");
      out.write("                </TD>\r\n");
      out.write("                <TD width=\"70%\">\r\n");
      out.write("                  <SELECT size=\"1\" name=\"sex\">\r\n");
      out.write("                    <OPTION value=\"m\">\r\n");
      out.write("                      Male\r\n");
      out.write("                    </OPTION>\r\n");
      out.write("                    <OPTION value=\"f\">\r\n");
      out.write("                      Female\r\n");
      out.write("                    </OPTION>\r\n");
      out.write("                  </SELECT>\r\n");
      out.write("                </TD>\r\n");
      out.write("              </TR>\r\n");
      out.write("              <TR>\r\n");
      out.write("                <TD>\r\n");
      out.write("                 &nbsp;  \r\n");
      out.write("                </TD>\r\n");
      out.write("                <TD>\r\n");
      out.write("                  <INPUT type=\"submit\" name=\"Submit\" value=\"Submit\">\r\n");
      out.write("                </TD>\r\n");
      out.write("              </TR>\r\n");
      out.write("            </TABLE>\r\n");
      out.write("          </FORM>\r\n");
      out.write("        </TD>\r\n");
      out.write("      </TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("  </BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
